### PR TITLE
add test for selecting policy

### PR DESCRIPTION
**Pull request by barnabasJ**
This test should mirror the behaviour I tested in my project before the refactor. 

# Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [ ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by barnabasJ** [comment]
I ran this test with ash from the commit in my project before updating and it didn't do what I was expecting. Maybe this only works with AshPostgres DataLayer.

I'm checking further.

**Comment by barnabasJ** [comment]
In the end the problem was a different one, I also had this condition in my policy

forbid_if(selecting(:internal_notes))

but the field was deselected here https://github.com/ash-project/ash/blob/f84d85cf20148f90afad9e1e44d4a2a115340257/lib/ash/actions/read/calculations.ex#L1026 before the query was authorized

**Comment by barnabasJ** [comment]
I used the `selecting` policy before field policies were available, but never changed it after introducing them into my project.

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
