### PR TITLE
docs: Update "Get Started" guide with an example

### PR DESCRIPTION
**Pull request by waseigo**
Added example of how to write the Representative ID directly into the Ticket during Ticket creation. Based on https://discord.com/channels/711271361523351632/1073248091324551228/1073249825363075102

# Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Chores
- [X] Documentation changes
- [ ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by zachdaniel** [comment]
Hey there! I think perhaps this would fit a bit better in the relationships guide? I just worry about potentially bloating what is a pretty small guide. We could link to the relationships guide from here though?

**Comment by waseigo** [comment]
The relationships guide already covers the `attribute_writable? true` option. From my point of view as an Ash beginner, I find it would be useful to mention this in the Getting Started guide -- after all, it's a very common thing a user would like to do, and it sensibly extends the Representative/Ticket example with a practical use case.

**Comment by zachdaniel** [comment]
@sevenseacat thoughts on adding this tidbit to the current getting started guide?

**Comment by sevenseacat** [comment]
I think it's a good idea! Do we want to encourage using `attribute_writable?` over `manage_relationship` though?

**Comment by zachdaniel** [comment]
Honestly, I think attribute writable is simpler in general, and if you're using a data layer like postgres then it is a good idea because there is little value in the application side lookup pattern that we do in manage_relationship and ash_postgres will give you a good error. We should probably recommend that in the general case, and mention that "you can still manage a belongs_to relationship with `manage_relationship` but if you only want to relate the record to the other record, `attribute_writable?` is simpler and easier to reason about."

**Pull request merged**
