### PR TITLE
feat: basic livebook generator and mix task

### PR DESCRIPTION
**Pull request by joshprice**
Basic Livebook generation and mix task.

Some refactoring required around utility functions, as the mermaid tasks are using too.

### CODE REVIEW

**Comment by zachdaniel** [comment]
I think that perhaps this should go in https://github.com/ash-project/ash_livebook? Mainly because there is going to be lots of livebook stuff over time. Alternatively we can make all the livebook stuff live in core...

**Comment by joshprice** [comment]
I thought about both ways and then settled on the simplest approach for now. At it's simplest it's really just generate a simple 1 page livebook, but this could easily get more fancy.

Happy to keep this in draft for further discussion.

**Comment by joshprice** [comment]
Update, 😆 I didn't realise you'd already made https://github.com/ash-project/ash_livebook will take a look.

**Comment by joshprice** [comment]
Think an extension is probably the place to keep smartcells, but not planning on using any for the basic generator.

**Comment by zachdaniel** [comment]
Yeah, but splitting up livebook responsibilities seems like a bad idea. We have `ash_livebook` started, so we could just put this in there. If we think `ash_livebook` will exist, we'll have to move this there later.

**Comment by zachdaniel** [comment]
@joshprice ash_livebook is pretty barren, just musings about a smart cell that doesn't actually do anything, but we can fix that :D

**Comment by joshprice** [comment]
If it is an extension, can it work globally? eg not at a resource by resource level, haven't seen an example of a globally applied extension that I can recall

**Comment by zachdaniel** [comment]
Well, the term is a bit nebulous. An actual "extension" only extends one thing, i.e a resource. Probably better to call things like `ash_postgres` and `ash_graphql` a "package" which contains a set of "extensions", and may include code that operates on groups of things.

**Comment by joshprice** [comment]
Even configuring at API level or above seems less desirable than deciding the livebook config at generation time with mix task args. So a package doesn't have to have any code config?

**Comment by zachdaniel** [comment]
Its just an elixir library at the end of the day. So "package" is wrong also lol. Its just a library on hex.

**Comment by joshprice** [comment]
Right, so could ash core depend on ash_livebook and therefore expose the functionality by default?

**Comment by zachdaniel** [comment]
It *could* but if we're going to do that we should just put it in core.

**Comment by joshprice** [comment]
Feel like this is probably the least friction approach from a user and usability perspective

**Comment by zachdaniel** [comment]
🤔 I think you're probably right, I'm leaning towards having it in core as well. Want to think it over a bit more.

**Pull request merged**
