### PR TITLE
ci: Improve CI Elixir/Erlang matrix

### PR DESCRIPTION
**Pull request by TheFirstAvenger**
Improve the Elixir/Erlang CI matrix. Copied matrix from Ecto, except bumped OTP 20 to OTP 21. Addresses #50.

### CODE REVIEW

**Comment by TheFirstAvenger** [comment]
`ETS` requires at least OTP 21 due to the `:ets.whereis` call, and I dropped the supported version in mix down to `~> 1.8`.

**Comment by TheFirstAvenger** [comment]
Looks like `persistent_term` is not available in 21.3.8.17, even though the OTP docs list it as 21.2/21.3.

**Comment by zachdaniel** [comment]
Nice, I didn't consider using `Map.put` to just ensure the field is manually there. Good catch :)

**Comment by zachdaniel** [comment]
Also, didn't realize that it wasn't the transformer sort that had the problem and that it was the runtime sorting.

**Comment by zachdaniel** [comment]
I specced the mix task as `no_return` in master, so perhaps pulling that into here may resolve the issue.

**Comment by TheFirstAvenger** [comment]
@zachdaniel nice, looks like that was the last issue, seems to be passing now on 1.8+

**Comment by zachdaniel** [comment]
Awesome work as always!
🚀 Thank you for your contribution! 🚀

**Pull request merged**
