### PR TITLE
Add constraints for handling empty values (#167)

### PR DESCRIPTION
**Pull request by zimt28**
Doesn't work yet, as `{:ok, value}` isn't a valid return for constraints yet.

### CODE REVIEW

**Comment by zimt28** [comment]
I just noticed that `String.trim/1` is actually smart enough to remove **any**  empty characters, not just regular spaces 🙄 So I think I will remove the `empty_values` and `empty_value_replacement` options again, or are they still helpful in any way? It should probably be up to the user how to deal with those details.

**Comment by zachdaniel** [comment]
We can start with just the `trim?` option and add back in customized empty characters/empty values if someone needs it.

**Comment by zachdaniel** [comment]
@zimt28 if you pull master, the `{:ok, new_value}` return type is now supported for `handle_constraints`

**Comment by zimt28** [comment]
@zachdaniel Great, anything left to do here? I could add a test tomorrow

**Comment by zachdaniel** [comment]
Yeah, go ahead and pull master back into your branch and then add a test then we can merge it.

**Comment by zimt28** [comment]
Whoops, that didn't work. Will send new PR!

**Pull request closed without merging**
