### PR TITLE
Reproducing a bug where the flow does not honor tenant

### PR DESCRIPTION
**Pull request by jechol**
# Contributor checklist

- [X] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [ ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

Flow doesn't seem to honor tenant.
This PR is to reproduce the bug.

```
mix test test/flow/tenant_test.exs
```

### CODE REVIEW

**Comment by jechol** [comment]
@zachdaniel Could you confirm if this is a bug or my misunderstanding?

**Comment by zachdaniel** [comment]
This does indeed look like a bug. Will merge and debug.

**Comment by zachdaniel** [comment]
Okay, so this isn't actually a bug, just a weird quirk of how destroy/update steps work in `Ash.Flow`. If the record being updated or destroyed evaluates to `nil`, the update/destroy step itself returns `nil`. So it is actually functioning as expected. I pushed up a fix just now for something else that is related. What you can do is specify `not_found_error? true` on a read step with `get? true` if you want the record not being present to be an error.

**Comment by zachdaniel** [comment]
Actually, nevermind, `not_found_error?` defaults to `true`. So the bug was that we weren't honoring that behavior.

**Pull request merged**
