### PR TITLE
`load` relationships on the results of bulk operations

### PR DESCRIPTION
**Pull request by davidebriani**
On paper, bulk operations (create, update, destroy) currently supports a `load` option used to specify "a load statement to apply to records", provided that the `return_records?` option is also set to `true` and records are returned.

The relevant changes and unit tests are added here to verify that the `load` statement is respected and it correctly loads relationships.

Note: loading relationships with pagination on results for bulk destroys is still not supported. Indeed, relationships are currently queried using a lateral join but after the resource deletion has happened, so it looks like nothing is related.

# Contributor checklist

- [x] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [ ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by zachdaniel** [comment]
So to confirm this is tests of the `load` option for bulk actions, and a fix for it not being honored on bulk destroys, is that right?

**Comment by davidebriani** [comment]
> So to confirm this is tests of the `load` option for bulk actions, and a fix for it not being honored on bulk destroys, is that right?

Yes. For clarification:
- Similar batches of unit tests are added for create/update/destroy to assert the expected behavior
- Bulk updates were already working
- Bulk creates currently break [here](https://github.com/ash-project/ash/blob/8dc0c2cb05e541cf73f0d18b3f7e315c5b0eadae/lib/ash/actions/create/bulk.ex#L189), resulting in errors such as `(Protocol.UndefinedError) protocol Enumerable not implemented for #Ash.Changeset...`, so it requires some troubleshooting
- Bulk destroys were working but not loading relationships. The code changes fix only non-paginated loads for now. Paginated loads currently return `%Ash.Page.Keyset{}` (instead of Offset) with`count: nil` and with no result.

**Comment by zachdaniel** [comment]
Loading relationships on bulk destroys is actually kind of a dodgy proposal. If you're doing anything that requires a lateral join, it will look like nothing is related because we load relationships after-the-fact 🥲. Someday in the future we can support doing it all in one query but that is dodgy for its own reasons.

**Comment by davidebriani** [comment]
Ah that's why, it makes sense! You spared me some good digging :)

I would rather not embark in a big rewriting on this PR, so my proposal is:
- we could keep the fix for non-paginated loads on destroys, if it makes sense. Regarding the paginated loads, for the moment I would just remove the introduced unit tests that are failing.
- we can focus on making bulk creates work.

**Comment by zachdaniel** [comment]
@davidebriani as for it failing there, that is likely just because that is where we "trigger" things w/ the `Stream.run`. Will need to look more into it. Is there anything else in the stacktrace that points to where it might be going wrong? I can look in the next few days otherwise.

Ultimately we allow folks to load relationships on destroy, so we should do our best to honor that. It will just have some unfortunate caveats for now.

**Comment by davidebriani** [comment]
@zachdaniel turns out I cannot read a stack trace :-P

The issue was that the bulk create assumed that `inputs` was a list of maps: a list of changesets was not actually contemplated, regardless of what the doc says.

**Comment by zachdaniel** [comment]
Hmm....I'm not sure that we actually want to accept a list of change sets. Its a pretty big change 🥶

**Comment by zachdaniel** [comment]
Might need to think about this more. Seeing as it was never working accepting change sets, perhaps we should walk it back and adjust the docs, and the current tests/behavior for now to account for that, and we can decide in a separate PR if we want to support that.

**Comment by davidebriani** [comment]
@zachdaniel I left out the changes regarding bulk creates, I'm only adding the unit tests here.

I'll open a new draft PR as a placeholder to discuss how we want to handle changeset inputs in bulk creates.

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
