### PR TITLE
improvement: add datetime_to_date function

### PR DESCRIPTION
**Pull request by pierrelegall**
Add `datetime_to_date` function.

Maybe it should be renamed `to_date` instead? :thinking:

Need an `ash_sql` update to support SQL executions of this function.

# Contributor checklist

- [ ] Chores
- [x] Documentation changes
- [x] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by zachdaniel** [comment]
Hmm...an interesting question here. What would the sqlite look like to execute this? Would `type(your_datetime, ^:date)` not work?

**Comment by pierrelegall** [comment]
- Postgres: `SELECT` DATE(a_date);`
- SQLite: `SELECT DATE(a_date);`

However, I didn't think about using `type`, I'll try this!

**Comment by pierrelegall** [comment]
`type(your_datetime, ^:date)` do the trick!

So I close the PR :)

**Comment by zachdaniel** [comment]
Thank you for the PR regardless, its always good when folks are interested in helping make things better for everyone 🙇

**Comment by pierrelegall** [comment]
A pleasure, it wasn't a loss of time, I learned about Ash writing this PR ;)

**Pull request closed without merging**
