### PR TITLE
Add `Negate` validation

### PR DESCRIPTION
**Pull request by marmor157**
Continue of work done in https://github.com/ash-project/ash/pull/587

> This PR adds negate validation that negates other validations. This allows to do things like negate(one_of(:attr, [:val1, :val2]).
> 
> Originally I wanted to name it not but when adding a builtin I've found that it might conflict with Kernel.not so I've renamed it to negate

### CODE REVIEW

**Comment by zachdaniel** [comment]
Looks great! One last note: let's make `describe` an optional callback with `@optional_callbacks describe: 1`, and then in the `negate` validation we can do something like this. Or perhaps even just raise an error if the target module does not implement  description.
```elixir
def init(opts) do
   Code.ensure_compiled!(module)
   
   if function_exported?(module, :describe, 1) do
      {:error, ...}
   else
      {:error, "unknown validation"}
   end
end
```

**Comment by marmor157** [comment]
`Code.ensure_compiled!(module)` is a great suggestion, thanks!

For the `@optional_callbacks` and erroring when there's do `describe/1` tho, what would be the advantage of that, over overridable default `describe/1` of `inspect(__MODULE__)`? IMO, when somebody creates his own validation and does not want to specify the description for it, the `inspect(__MODULE__)` is good fallback as it at least specifies which validation failed, rather than forcing developer to write the description.

**Comment by zachdaniel** [comment]
What we want to avoid is leaking module names in error messages. Perhaps we could have a middle ground and make a special type of `:unknown` error with a special message, and return that. We don’t ever show unknown errors to users.

**Comment by zachdaniel** [comment]
Although what we should actually do, come to think of it, is write a verifier on the resource DSL that checks all usage and raises a *compile time warning or error* if the describe callback isn’t defined.

**Comment by marmor157** [comment]
> Although what we should actually do, come to think of it, is write a verifier on the resource DSL that checks all usage and raises a compile time warning or error if the describe callback isn’t defined.

Isn't it what `init/1` is doing? I've added this validation inside it and tested it, seems to work ok. 
Although I'm not entirely happy about `with_description` implementation now :/

**Comment by zachdaniel** [comment]
Nice work! Like the consistency changes on returning errors. Ready to merge?

**Comment by marmor157** [comment]
Ready 🎉

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
