### PR TITLE
Adds a test to ensure authorization occurs when the actor is set and …

### PR DESCRIPTION
**Pull request by hanrelan**
It seems that `authorize?: true` isn't being set when the actor is set, even `authorization` is `:by_default`.

I wasn't sure how to fix the issue, but this adds a (sort of janky) failing test for that case.

# Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [ x ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Comment by zachdaniel** [comment]
This is....actually kind of a conundrum/problem. The basic issue here is that we don't *know* what the api is yet.

```elixir
Post
|> Ash.Changeset.for_create(:title_is_authorization, %{}, actor: :an_actor)
```

Nowhere here have we been given an api, so we don't know if we're authorizing yet. This is actually a pretty significant issue, because the general pattern is this:

```elixir
def change(changeset, _opts, context) do
  Ash.Changeset.before_action(changeset, fn changeset -> 
    # do something with context
    context.authorize?
  end)
end
```

so we close over the initial value and there is no good way to get the proper value (technically, inside the before action hook you could do `changeset.context.private.authorize?` but thats of course not a good idea.

I'm going to have to think about this. I fear that any fix to tighten this up is going to require a non-trivial breaking change.

**Comment by zachdaniel** [comment]
Yeah, unfortunately, a true fix for this is going to have to wait until some redesigns that will have to happen with 3.0. In the meantime, the only short term solution we have is to *remove* the `authorize?` key from the context unless it was explicitly provided.

**Comment by zachdaniel** [comment]
Nope, can't do that, as it is in itself a breaking change (just tried it, had to revert). For now, I've added an `api` option to `Ash.Changeset.for_*` that will allow you to pass the api, which should produce the correct values there in all cases. This will be fixed without the need to do that in the 3.0 release.

**Comment by zachdaniel** [comment]
Okay, so there is a way that you can get around this using some upcoming 3.0 work that is currently in `main`, although not documented. You'd be using a small part that is unlikely to change in any meaningful way before 3.0 comes out.

In each resource, do the following:

```elixir
use Ash.Resource, ..., api: TheApiTheResourceIsIn
```

**Comment by hanrelan** [comment]
Got it - makes sense. Will set it up to pass the Api to the resource everywhere (or potentially just use `authorize?: true`, though I'm not sure if that doesn't help for extensions like ash_graphql )

**Comment by zachdaniel** [comment]
You can use the `use Ash.Resource, ..., api: Api` currently (if you are using `main`) I will release the changes tomorrow. That will allow you to avoid passing the api to all changesets.

**Pull request merged**
