### PR TITLE
Fix bulk upsert condition

### PR DESCRIPTION
**Pull request by adonig**
While working on a bulk create operation, I encountered an issue where the upsert condition worked correctly for managed relationships but failed for the primary resource being upserted. Upon investigation, I traced the problem back to the base changeset, which lacked the necessary filter for the upsert condition.

Adding the missing filter, however, caused the existing bulk create test to fail. Further debugging revealed that the bulk create test had never actually functioned correctly - it was missing a require Ash.Expr statement. It's unclear how the test passed previously, given that the required macros were missing.

# Contributor checklist

- [x] Bug fixes include regression tests
- [x] Chores
- [x] Documentation changes
- [x] Features include unit/acceptance tests
- [x] Refactoring
- [x] Update dependencies

### CODE REVIEW

**Review by zachdaniel — APPROVED** [review]

**Review by zachdaniel — DISMISSED** [review]

**Comment by zachdaniel** [comment]
I approved, but it looks like some tests are still failing.

**Comment by adonig** [comment]
Strange, I will check.

**Comment by adonig** [comment]
I've reverted my changes to `bulk.ex` and added a test case to illustrate the issue with the current code.

The test case creates an instance of a `Product` resource that has a `has_one` relationship with a `Price` resource. In the test, we attempt to update (upsert) the product with a new price while using `upsert_condition: expr(false)`. According to this condition, the upsert should not occur, and the product should retain its original price. However, the test fails because the current code does not correctly respect the upsert_condition, resulting in the product being incorrectly associated with the new price.

```
  1) test respects upsert_condition despite we have a relationship (Ash.Test.Actions.BulkCreateTest)
     test/actions/bulk/bulk_create_test.exs:751
     Assertion with == failed
     code:  assert still_the_same_product.price.min == product.price.min
     left:  234
     right: 123
     stacktrace:
       test/actions/bulk/bulk_create_test.exs:804: (test)
```

**Comment by adonig** [comment]
I've reintroduced the upsert_condition filter to the base changeset. With this change, the new test (which I modified to check for an empty records list) now passes successfully. However, the test "test can upsert with list" fails with the strange error we encountered yesterday:

```
  1) test can upsert with list (Ash.Test.Actions.BulkCreateTest)
     test/actions/bulk/bulk_create_test.exs:697
     ** (Ash.Error.Unknown) Unknown Error

     * upsert_conflict(:title) not implemented for data source
       (ash 3.4.1) deps/splode/lib/splode.ex:268: Ash.Error.to_error/2
       (ash 3.4.1) lib/ash/actions/helpers.ex:15: Ash.Actions.Helpers.rollback_if_in_transaction/3
       (ash 3.4.1) lib/ash/actions/create/bulk.ex:1207: anonymous fn/10 in Ash.Actions.Create.Bulk.run_batch/9
       (elixir 1.17.2) lib/enum.ex:1268: anonymous fn/3 in Enum.flat_map/2
       (stdlib 6.0.1) maps.erl:860: :maps.fold_1/4
       (elixir 1.17.2) lib/enum.ex:2543: Enum.flat_map/2
       (ash 3.4.1) lib/ash/actions/create/bulk.ex:562: Ash.Actions.Create.Bulk.do_handle_batch/11
       (ash 3.4.1) lib/ash/actions/create/bulk.ex:162: anonymous fn/12 in Ash.Actions.Create.Bulk.do_run/5
       (elixir 1.17.2) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
       (elixir 1.17.2) lib/stream.ex:1879: anonymous fn/3 in Enumerable.Stream.reduce/3
       (elixir 1.17.2) lib/stream.ex:289: Stream.after_chunk_while/2
       (elixir 1.17.2) lib/stream.ex:1908: Enumerable.Stream.do_done/2
       (elixir 1.17.2) lib/stream.ex:1891: Enumerable.Stream.do_each/4
       (elixir 1.17.2) lib/stream.ex:943: Stream.do_transform/5
       (elixir 1.17.2) lib/enum.ex:4423: Enum.reverse/1
       (elixir 1.17.2) lib/enum.ex:3748: Enum.to_list/1
       (ash 3.4.1) lib/ash/actions/create/bulk.ex:186: Ash.Actions.Create.Bulk.do_run/5
       (ash 3.4.1) lib/ash/actions/create/bulk.ex:83: Ash.Actions.Create.Bulk.run/5
       (ash 3.4.1) lib/ash.ex:2224: Ash.bulk_create!/4
       test/actions/bulk/bulk_create_test.exs:731: Ash.Test.Actions.BulkCreateTest."test can upsert with list"/1
       (ex_unit 1.17.2) lib/ex_unit/runner.ex:485: ExUnit.Runner.exec_test/2
       (stdlib 6.0.1) timer.erl:590: :timer.tc/2
       (ex_unit 1.17.2) lib/ex_unit/runner.ex:407: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4
     code: Ash.bulk_create!(
     stacktrace:
       (ash 3.4.1) lib/ash.ex:2243: Ash.bulk_create!/4
       test/actions/bulk/bulk_create_test.exs:731: (test)
```

**Comment by adonig** [comment]
I'm still working on fixing the failing test. You mentioned in Discord that "`upsert_conflict/1` should be replaced by the time it gets to where it is" and that "something is happening that is causing `upsert_conflict` not to be replaced with the actual value." Could you clarify which code is responsible for replacing the `upsert_conflict/1` function? I want to investigate why this replacement isn't happening anymore.

**Comment by adonig** [comment]
Never mind, I see that you've fixed it in the main branch. Awesome! 🥳

**Pull request merged**
