### PR TITLE
Add accept_default option

### PR DESCRIPTION
**Pull request by zimt28**
https://github.com/ash-project/ash/issues/249

### CODE REVIEW

**Comment by zachdaniel** [comment]
Lets add some basic tests for this in here: https://github.com/ash-project/ash/blob/main/test/resource/actions/actions_test.exs

**Comment by zimt28** [comment]
Done, I've also simplified the code a bit. I'm not sure why the test fails as I haven't changed anything regarding primary actions

**Comment by zachdaniel** [comment]
Try setting the test to `async?: false`? It may be a conflict with overriding that posts module in each test

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
