### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by vbrazo**
# Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Documentation changes
- [ ] Features include unit/acceptance tests
- [x] Update dependencies

Hey Zach. I'm just updating other dependencies. Let me know if it makes sense.

### CODE REVIEW

**Comment by vbrazo** [comment]
@zachdaniel should we consider adding dependabot?

**Comment by zachdaniel** [comment]
I'd be happy to add it, I wasn't aware that it would work with elixir dependencies :D

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Comment by vbrazo** [comment]
@zachdaniel https://dependabot.com/#languages

**Comment by zachdaniel** [comment]
Excellent! I believe I've just enabled it across the ash-project organization, so hopefully that's all that needs to be done.

**Pull request merged**
