### PR TITLE
Add equal_to, not_equal_to to Validation.Compare

### PR DESCRIPTION
**Pull request by jechol**
# Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [X] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by zachdaniel** [comment]
Hmm...we currently have `validate attribute_equals(:foo, :bar)` and `validate attribute_does_not_equal`, I think it would make sense to use those instead?

**Comment by jechol** [comment]
> Hmm...we currently have `validate attribute_equals(:foo, :bar)` and `validate attribute_does_not_equal`, I think it would make sense to use those instead?

1. `attribute_equals` doesn't work for Decimal when the precision differs.
2. I prefer to consistently use `compare` rather than mixing `attribute_equals` and `compare` for Decimal.

**Comment by zachdaniel** [comment]
I think the fix is to use `Comp.equal?` in `attribute_equals` and `attribute_does_not_equal` in that case then.

**Comment by jechol** [comment]
Oh, I see. Should I go ahead and create a PR for that?

**Pull request closed without merging**
