### PR TITLE
added description to actions and relationships

### PR DESCRIPTION
**Pull request by mario-mazo**
### Contributor checklist

- [x] My commit messages follow the [Conventional Commit Message Format](https://gist.github.com/stephenparish/9941e89d80e2bc58a153#format-of-the-commit-message)
      For example: `fix: Multiply by appropriate coefficient`, or
      `feat(Calculator): Correctly preserve history`
      Any explanation or long form information in your commit message should be
      in a separate paragraph, separated by a blank line from the primary message
- [ ] Bug fixes include regression tests
- [ ] Features include unit/acceptance tests

### CODE REVIEW

**Comment by mario-mazo** [comment]
closes #58 
Not all resources have description but perhaps we can split in multiple PRs to avoid mega PRs

**Comment by zachdaniel** [comment]
For consistency, I'd say to add the description to the "global_opts", that way it is clear from the documentation that each relationship shares it. We probably also want to add that same global options pattern to actions, if you're up for it.

**Comment by mario-mazo** [comment]
I dont see how adding to `@global_opts` would make it more consistent  if what you mean is adding it `Ash.Resource.Relationships.SharedOptions` then it makes sense.

The only disadvantage I see is that we would lose the resource specific description like
"An optional description for the **many_to_many** relationship" and instead we would get generic ones

- "An optional description for the relationship" 
- "An optional description for the action" <- in case we add a SharedOptions to action resource

**Comment by zachdaniel** [comment]
Yeah, shared options is what I was referring to, sorry :) But I think that is fine, if you're looking at the docs you'll see the description in the context of the action type you are looking at, and using shared opts helps make it really clear when something is unique to a given action type.

**Review by zachdaniel — APPROVED** [review]

**Pull request merged**
