### PR TITLE
docs: Update get-started.md

### PR DESCRIPTION
**Pull request by laiboonh**
# Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Chores
- [x] Documentation changes
- [ ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by zachdaniel** [comment]
Hey there! So we reference the `:create` action above, but call the action `:open`. Let's change them both to `:create` for simplicity.

**Comment by laiboonh** [comment]
> Hey there! So we reference the `:create` action above, but call the action `:open`. Let's change them both to `:create` for simplicity.

Not sure i understand what you are saying. Calling `:open` action seems perfectly fine to me because at this stage of the doc we are already past the stage of using `:create` to create a ticket.

https://ash-hq.org/docs/guides/ash/latest/tutorials/get-started#open-a-ticket is already using `:open`
https://ash-hq.org/docs/guides/ash/latest/tutorials/get-started#open-a-ticket should continue using `:open`

**Comment by zachdaniel** [comment]
Right you are :) Been a while since I visited that doc. Thanks for the correction!

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
