### PR TITLE
test: pass in arguments to validation

### PR DESCRIPTION
**Pull request by barnabasJ**
I had this problem in my code, and passing the query argument made it work. I don't think this is 100% correct in this case. 
The added test is also not doing what I would expect it to. The calculation is not loaded and I don't know why.  Maybe this gives you enough information for a fix. Or if it is more involved, maybe you could give me a couple pointers. 

Thanks

# Contributor checklist

- [ ] Bug fixes include regression tests
- [ ] Chores
- [ ] Documentation changes
- [ ] Features include unit/acceptance tests
- [ ] Refactoring
- [ ] Update dependencies

### CODE REVIEW

**Comment by zachdaniel** [comment]
What is the issue that you were seeing? Can I see an example of some code that doesn't work? The reason that passes an empty map there is because when a calculation is loaded without arguments we pass an empty map by default. Perhaps you are loading `:calc` instead of `calc: [arg1: value]`?

**Comment by zachdaniel** [comment]
What is the stacktrace of the error?

**Comment by barnabasJ** [comment]
> 

```
  2) test full text search (Demo.Inventory.Resources.SearchTest)
     test/demo/inventory/resources/search_test.exs:7
     ** (CaseClauseError) no case clause matching: {#Ash.Query<resource: Demo.Inventory.Resources.Search, arguments: %{lang: :de, query: "Deutschland"}, filter: #Ash.Filter<matches_de(%{ash: %{constraints: [], type: Ash.Type.Boolean}, query: "Deutschland"})>, sort: [{#Ash.Resource.Calculation.Expression<[expr: fragment("ts_rank_cd(\n  searchable_de,\n  websearch_to_tsquery(?),\n  4\n)\n",  {:_arg, :query})]> - %{query: "Deutschland"}, :asc}, {:inventory_id, :asc}, {:inventory_type, :asc}, {:destination_id, :asc}, {:destination_type, :asc}], limit: 251, calculations: %{headline_de: #Ash.Resource.Calculation.Expression<[expr: fragment("ts_headline(\n  'german',\n  CONCAT(name, ' ', destination_de),\n  websearch_to_tsquery(?),\n'StartSel=<h3>,StopSel=</h3>,MinWords=25,MaxWords=75'\n)\n",  {:_arg, :query})]> - %{query: "Deutschland"}, match_rank_de: #Ash.Resource.Calculation.Expression<[expr: fragment("ts_rank_cd(\n  searchable_de,\n  websearch_to_tsquery(?),\n  4\n)\n",  {:_arg, :query})]> - %{query: "Deutschland"}, matches_de: #Ash.Resource.Calculation.Expression<[expr: fragment("(searchable_de @@ websearch_to_tsquery(?))\n",  {:_arg, :query})]> - %{query: "Deutschland"}}, errors: [%Ash.Error.Unknown.UnknownError{error: "load: Argument query is required", field: nil, changeset: nil, query: nil, error_context: [], vars: [], path: [:load], stacktrace: #Stacktrace<>, class: :unknown}]>, []}
     code: |> Demo.Support.read()
     stacktrace:
       (ash 2.6.9) lib/ash/engine/request.ex:1049: Ash.Engine.Request.do_try_resolve_local/4
       (ash 2.6.9) lib/ash/engine/request.ex:917: Ash.Engine.Request.do_try_resolve/5
       (elixir 1.14.3) lib/enum.ex:4751: Enumerable.List.reduce/3
       (elixir 1.14.3) lib/enum.ex:2514: Enum.reduce_while/3
       (ash 2.6.9) lib/ash/engine/request.ex:983: Ash.Engine.Request.do_try_resolve_local/4
       (ash 2.6.9) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
       (ash 2.6.9) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
       (ash 2.6.9) lib/ash/engine/engine.ex:661: Ash.Engine.advance_request/2
       (ash 2.6.9) lib/ash/engine/engine.ex:567: Ash.Engine.fully_advance_request/2
       (ash 2.6.9) lib/ash/engine/engine.ex:508: Ash.Engine.do_run_iteration/2
       (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ash 2.6.9) lib/ash/engine/engine.ex:268: Ash.Engine.run_to_completion/1
       (ash 2.6.9) lib/ash/engine/engine.ex:213: Ash.Engine.do_run/2
       (ash 2.6.9) lib/ash/engine/engine.ex:116: Ash.Engine.run/2
       (ash 2.6.9) lib/ash/actions/read.ex:170: Ash.Actions.Read.do_run/3
       (ash 2.6.9) lib/ash/actions/read.ex:90: Ash.Actions.Read.run/3
       (demo 0.1.0) lib/demo/support.ex:1: Demo.Support.read/2
       test/demo/inventory/resources/search_test.exs:35: (test)
```

**Comment by zachdaniel** [comment]
I don't fully understand the issue yet, but one thing I can say for sure is that we don't want to pass the query arguments to the calculation, those are meant to be separate.

**Comment by barnabasJ** [comment]
Something was missing in the test, it now triggers the same error I was getting.

**Comment by barnabasJ** [comment]
> I don't fully understand the issue yet, but one thing I can say for sure is that we don't want to pass the query arguments to the calculation, those are meant to be separate.

I got this impression during debugging, but I didn't fully understand the code TBH :wink:

**Comment by zachdaniel** [comment]
If you remove the change to pass query arguments into the calculation argument validator, I'll merge and fix it :D Probably need to poke around to find whats going on.

**Comment by barnabasJ** [comment]
> If you remove the change to pass query arguments into the calculation argument validator, I'll merge and fix it :D Probably need to poke around to find whats going on.

Thank you :heart:

**Comment by zachdaniel** [comment]
fixed in main

**Pull request merged**
