### PR TITLE
feature: generate mermaid entity relationship diagrams from a given api

### PR DESCRIPTION
**Pull request by joshprice**
Initial cut of generating ERDs in Mermaid from a given API. Other things to look at:

- show attrs
- show private attrs
- show private relships
- show calcs, aggs
- mix task to generate similar to flow chart

# Contributor checklist

- [x] Features include unit/acceptance tests

### CODE REVIEW

**Comment by zachdaniel** [comment]
A couple interesting things here. I'd generally go with `string[]` as opposed to `[string]`. Aside from that, it looks like mermaid doesn't support special chracters in types, so we're going to have to (at least for now) do something like `stringArray` or `ArrayOfString`.

The last thing to talk about is the relationships. I definitely see what you're saying about not deduplicating the relationships being problematic, but its also typically very important information. Resource A may have multiple relationships to Resource B. Perhaps there is a creative way to show that, if we can label the edges in that way. We could group them up, and show one line both ways, that shows all of the relationship names, potentially?

**Comment by zachdaniel** [comment]
Most importantly: This is *awesome* 🥳

**Comment by zachdaniel** [comment]
Okay, so if we switch to class diagrams, I think we get better features in general: https://mermaid-js.github.io/mermaid/#/classDiagram?id=syntax

Including special characters

**Comment by zachdaniel** [comment]
Here is an example of what that looks like, with array types and labeled relationships: https://mermaid.live/edit#pako:eNptkMFugzAMhl8l8pmWARttc97uk6pdNqbKJQGiQYwSU6mqePcF6NZtmi-Jf3_5HfsCJSkNEsoWvX80WDvsCitCzIp48dqJy6JMsWdnbC0sdnoRx5_0M3n-hz6SOv8V394FY-1_mczNaLWixUiKPhw-EhWeyBnWhylf0BmY0fmRFDhwQ-7GqsMQCld_iKDTrkOjwqjz_wrgRocZQIarQvdRQGHHwA29QtZPyjA5kBW2XkcQzGl_tiVIdoP-gq7r-qZ6tK9Et7wlVDqYXIDP_bTk2ngOLUqylaknfXBtkBvm3ss4nsrr2nAzHNcldbE3qkHHzWmXx3mabzHNdL7J8CHLVHlMdtsqvU8qtblLUoRxHD8B1x2VJw

**Comment by zachdaniel** [comment]
This looks great! Is this read to merge @joshprice ?

**Comment by joshprice** [comment]
I think so, it's missing the mix tasks. Your call if you want to merge this and I can start a new PR.

**Comment by zachdaniel** [comment]
Lets merge it :). As for the mix task, I'd take a look at the `generate_flow_charts` task for inspiration.

**Review by zachdaniel — APPROVED** [review]

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
