### PR TITLE
Sorting for hex documentation added

### PR DESCRIPTION
**Pull request by couhajjou**
# Contributor checklist

- [ ] ~~Bug fixes include regression tests~~ - Not Applicable
- [ ] ~~Chores~~ - Not Applicable
- [ ] ~~Documentation changes~~  - Not Applicable
- [x] Features include unit/acceptance tests 
    - Finished in 51.2 seconds (46.7s async, 4.4s sync)
    - 854 tests, 0 failures, 2 excluded
- [ ] ~~Refactoring~~  - Not Applicable
- [ ] ~~Update dependencies~~  - Not Applicable

### CODE REVIEW

**Comment by zachdaniel** [comment]
I'm going to have to see how/if this affects our https://ash-hq.org documentation indexing before I merge it. Thanks for the PR!

**Comment by zachdaniel** [comment]
Just going to merge it and see what happens 😂

**Comment by zachdaniel** [comment]
Ah, there are merge conflicts. Could you address those and then I'll merge?

**Comment by couhajjou** [comment]
Done !

**Comment by zachdaniel** [comment]
🚀 Thank you for your contribution! 🚀

**Pull request merged**
